### ISSUE TITLE
Fails in SBCL 1.3.1.188-f7d76e5

### ISSUE THREAD

**Issue by quicklisp** [cosmos72/stmx#11]
I get this:

    ; caught ERROR:
    ;   READ error during COMPILE-FILE: Lock on package SB-VM violated when interning OFFSET-NEXT while in package SB-TRANSACTION.

More info is here: http://report.quicklisp.org/2016-01-11/failure-report/stmx.html#stmx

**Comment by cosmos72** [comment]
If I understand correctly, this happens only with the latest development snapshot of sbcl, not with any release version (including 1.3.1).

SB-VM::OFFSET-NEXT is used to simplify the function to disassemble the new x86 CPU instruction xbegin.
I need to ask on sbcl mailing list what's the best way to define disassembling functions for CPU instruction that contain jump addresses.

**Comment by quicklisp** [comment]
That's right, only a problem in development SBCL.

**Comment by cosmos72** [comment]
This now happens also with sbcl 1.3.2 - see issue #12.
Fixed in commit 183768d6aa995f5a529affeb899aed70a6463fc1
