### ISSUE TITLE
Does not build - emit-skip issue

### ISSUE THREAD

**Issue by quicklisp** [cosmos72/stmx#19]
Same as (or similar to) #17 - with the latest SBCL git checkout, and the latest stmx checkout, I get a failure due to package locks on sb-vm.

It looks to me like `(stmx.asm::compile-if-instruction-defined 'xbegin)` evaluates to `(:OR)` and combined with `#-` it tries to read the form that references `sb-vm::emit-skip`.

Build log here: http://report.quicklisp.org/2020-02-24/failure-report/stmx.html#stmx

**Comment by cosmos72** [comment]
Which branch of stmx sources are you using?
I recently pushed a fix to the master branch, but I think I forgot to updat the stable branch (which quicklisp is configured to downlaoad)

**Comment by cosmos72** [comment]
Found.
It's an internal change in sbcl, which confuses stmx detection of x86-64 instructions 'xbegin' 'xend' ... that were added to sbcl 1.4.10 (previously, these instructions were defined by stmx itself).

Such detection code is obviously examining sbcl internals in unsupported ways, and infact it keeps breaking.

I guess it must be rewritten as "assume that sbcl >= 1.4.10 defines 'xbegin' 'xend'... and assume that sbcl < 1.4.10 does not define them"

**Comment by cosmos72** [comment]
Fixed, both in master branch (commit f8de8cc784585eeb917d5474af5b8f9510fa4bd6)
and in stable branch pulled by quicklisp (commit bf11fcd4a01e3bf424f0e6330dcdda7b103d01f1)
