### ISSUE TITLE
Does not build in sbcl 2.0.9 -  EAX-OFFSET lock

### ISSUE THREAD

**Issue by quicklisp** [cosmos72/stmx#20]
http://report.quicklisp.org/2020-09-28/failure-report/stmx.html#stmx has the log. I get this:

`;   READ error during COMPILE-FILE: Lock on package SB-VM violated when interning EAX-OFFSET while in package STMX.ASM.`

**Comment by cosmos72** [comment]
Thanks! I will investigate this.

**Comment by cosmos72** [comment]
fixed in commit 59e1931155a257cb1f0e500dc1b722e2262fe522 (stable branch, the one pulled by quicklisp)
and also fixed in master branch
