### ISSUE TITLE
Test suite failure on SBCL 2.3.2 with latest Quicklisp dist

### ISSUE THREAD

**Issue by swapneils** [cosmos72/stmx#28]
Run on Windows.

This might be related to https://github.com/cosmos72/stmx/issues/26, but as I understand a fix was merged into this repo for that issue (and I installed after making a git clone in `quicklisp/local-packages`, so not sure why it's still occurring.

```
 --------------------------------
 TMAP-ROLLBACK in TMAP-SUITE []: 
      Unexpected Error: #<SIMPLE-ERROR "STMX internal error!~&  ~A" {100A221773}>
STMX internal error!
  stmx:*current-thread* contains a stale value:
   found #<SB-THREAD:THREAD "main thread" RUNNING {10010A8143}>
   expecting #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {100DFA01D3}>
Typical cause is:
   new threads were created with implementation-specific functions,
   as for example (sb-thread:make-thread) or (mp:process-run-function),
   that do not apply thread-local bindings stored in
   bordeaux-threads:*default-special-bindings*
Solution:
   use (bordeaux-threads:make-thread) instead..
```

**Comment by cosmos72** [comment]
Hi @swapneils,
at the moment I don't have a Windows system for reproducing this issue.

Two questions:
1. how do you trigger this error? is `(asdf:test-system "stmx")` enough, or you need something else - and in case, what?
2. does it happen also on other operating systems?

**Comment by swapneils** [comment]
May have been an installation issue, reinstalling from git resulted in both `asdf:test-system` and `fiveam:run!` passing.
