### ISSUE TITLE
Accepting donation?

### ISSUE THREAD

**Issue by cmpitg** [cosmos72/stmx#9]
Dear Massimiliano Ghilardi,

My apologies for this improper issue.  Please disregard if it is inappropriate.  I just want to thank you for your hardwork in creating, actively developing, and maintaining this awesome project.  I have used STMX in my recent projects with great success.  I'd like to donate to the project as my expression of gratitude.  Would you accept any form of donation?

Best regards,
Duong

**Comment by cosmos72** [comment]
Thanks for the offer :) It's an interesting idea, and not inappropriate. I am not a lawyer or a business consultant, so I need to ask about the Italian taxes and laws... at first glance, for "moderate amounts" it should be easy.

An unrelated question, if I may ask: in what kind of projects did you use STMX? Some feedback would be useful too :)

Regards,
Massimiliano

**Comment by cmpitg** [comment]
My pleasure :-). Please let me know when things are good.

We use STMX in an information distribution platform that needs to process around 20K of requests per second on the average. For each request, we need to do lots of computations to produce the corresponding and post-processing for other components. The computations involve mostly transformation with large chunks of data. The previous version was written in Erlang that took advantage of Actor model, which turned out to be too much overhead as the cost of message passing was much greater than the cost of computation. So we decided to rewrite the system with shared memory-based approach and ultimately chose Common Lisp/SBCL and STMX. Your thoughtful APIs and well-written docs were great help. CLOS was used at first but as soon as STMX supported struct, we immediately switched to it, simplifying the interface. We also utilized [cl-annot](https://github.com/m2ym/cl-annot) to keep the code as clean and maintainable as much as possible. The new version has been running for more than a month now, so far so good. We haven't actually run into any technical problems that are particular related to STMX, but we'll keep you informed if there is.

All the best,
Duong

**Comment by cosmos72** [comment]
Added a "donate" button to stmx.org, and a link in github project README
